import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import AsideBar from "./components/layout/aside"

const roboto = Roboto({ subsets: ['latin'], weight: '300'})

export const metadata: Metadata = {
  title: 'CassinoUI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className='w-screen h-screen bg-padraoCinzaE flex flex-row'>
          <AsideBar/>
          {children}
        </div>
      </body>
    </html>
  )
}
